/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
	val cucumberVersion = "7.14.0"
	implementation("io.cucumber:cucumber-java:$cucumberVersion")
	implementation("io.cucumber:cucumber-junit-platform-engine:$cucumberVersion")
	implementation("org.junit.platform:junit-platform-suite")
	implementation("org.junit.platform:junit-platform-suite-api")
    implementation("io.cucumber:cucumber-spring:$cucumberVersion")
	// Use JUnit Jupiter for testing.
	testImplementation(libs.junit.jupiter)
	testImplementation(libs.junit.jupiter.api)
	testImplementation(libs.junit.jupiter.engine)
	testImplementation(libs.junit.vintage.engine)
	testImplementation("org.junit.platform:junit-platform-suite-api")
	testImplementation("org.junit.platform:junit-platform-suite")
	testImplementation("io.cucumber:cucumber-java:$cucumberVersion")
	testImplementation("io.cucumber:cucumber-junit-platform-engine:$cucumberVersion")
	testImplementation("io.cucumber:cucumber-spring:$cucumberVersion")
	testImplementation("org.springframework:spring-context:6.1.14")
	testImplementation("org.springframework:spring-test:6.1.14")
    
    // Use Selenium for web testing
    testImplementation(libs.selenium.java)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
	testRuntimeOnly("org.junit.platform:junit-platform-suite-api")
	testRuntimeOnly("org.junit.platform:junit-platform-suite")
    testRuntimeOnly("io.cucumber:cucumber-java:$cucumberVersion")
    testRuntimeOnly("io.cucumber:cucumber-junit-platform-engine:$cucumberVersion")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.selenium.chrome.driver)
}

sourceSets {
    test {
        java.srcDirs.add(File("src/test/java"))
        resources.srcDirs.add(File("src/test/resources"))
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    systemProperty("cucumber.object-factory", "io.cucumber.core.backend.DefaultObjectFactory")
    systemProperty("cucumber.plugin", "pretty, summary")
}
